name: CI

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  vm:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a set of commands using the runners shell
      - name: Start build
        run: echo Beginning build
  container:
    runs-on: ubuntu-latest
    container: debian:12
    steps:
      - uses: actions/checkout@v4
      - name: Build Asterisk
        run: |
          cd /usr/local/src
          apt-get update -y
          apt-get install -y wget php php-xml
          wget https://raw.githubusercontent.com/InterLinked1/phreakscript/refs/heads/master/phreaknet.sh
          chmod +x phreaknet.sh
          ./phreaknet.sh make
          phreaknet install --version=master
          ls -la
      - name: Generate documentation
        run: |
          cp *.php /usr/src/asterisk-git
          cd /usr/src/asterisk-git
          ./astdocgen.php -f doc/core-en_US.xml -x -s > /tmp/astdocgen.xml
          ./astdocgen.php -f /tmp/astdocgen.xml -h > doc/index.html
